import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class IndianCitiesService {
  private cities: string[] = [
    // Major Cities
    'Mumbai, Maharashtra',
    'Delhi, Delhi',
    'Bangalore, Karnataka',
    'Hyderabad, Telangana',
    'Chennai, Tamil Nadu',
    'Kolkata, West Bengal',
    'Pune, Maharashtra',
    'Ahmedabad, Gujarat',
    'Jaipur, Rajasthan',
    'Surat, Gujarat',
    'Lucknow, Uttar Pradesh',
    'Kanpur, Uttar Pradesh',
    'Nagpur, Maharashtra',
    'Indore, Madhya Pradesh',
    'Thane, Maharashtra',
    'Bhopal, Madhya Pradesh',
    'Visakhapatnam, Andhra Pradesh',
    'Patna, Bihar',
    'Vadodara, Gujarat',
    'Ghaziabad, Uttar Pradesh',
    'Ludhiana, Punjab',
    'Agra, Uttar Pradesh',
    'Nashik, Maharashtra',
    'Faridabad, Haryana',
    'Meerut, Uttar Pradesh',
    'Rajkot, Gujarat',
    'Varanasi, Uttar Pradesh',
    'Srinagar, Jammu and Kashmir',
    'Amritsar, Punjab',
    'Chandigarh, Chandigarh',
    'Jodhpur, Rajasthan',
    'Raipur, Chhattisgarh',
    'Allahabad, Uttar Pradesh',
    'Coimbatore, Tamil Nadu',
    'Jabalpur, Madhya Pradesh',
    'Gwalior, Madhya Pradesh',
    'Vijayawada, Andhra Pradesh',
    'Madurai, Tamil Nadu',
    'Guwahati, Assam',
    'Chandigarh, Punjab',
    'Hubli, Karnataka',
    'Aurangabad, Maharashtra',
    'Mysore, Karnataka',
    'Ranchi, Jharkhand',
    'Bhubaneswar, Odisha',
    'Salem, Tamil Nadu',
    'Tiruchirappalli, Tamil Nadu',
    'Bareilly, Uttar Pradesh',
    'Moradabad, Uttar Pradesh',
    'Durgapur, West Bengal',
    'Jalandhar, Punjab',
    'Bhilai, Chhattisgarh',
    'Warangal, Telangana',
    'Mira-Bhayandar, Maharashtra',
    'Gorakhpur, Uttar Pradesh',
    'Bikaner, Rajasthan',
    'Amravati, Maharashtra',
    'Noida, Uttar Pradesh',
    'Jamshedpur, Jharkhand',
    'Bhilwara, Rajasthan',
    'Cuttack, Odisha',
    'Firozabad, Uttar Pradesh',
    'Kochi, Kerala',
    'Nellore, Andhra Pradesh',
    'Bhavnagar, Gujarat',
    'Dehradun, Uttarakhand',
    'Dhanbad, Jharkhand',
    'Durg, Chhattisgarh',
    'Asansol, West Bengal',
    'Rourkela, Odisha',
    'Nanded, Maharashtra',
    'Kolhapur, Maharashtra',
    'Ajmer, Rajasthan',
    'Akola, Maharashtra',
    'Gulbarga, Karnataka',
    'Jamnagar, Gujarat',
    'Ujjain, Madhya Pradesh',
    'Loni, Uttar Pradesh',
    'Siliguri, West Bengal',
    'Jhansi, Uttar Pradesh',
    'Ulhasnagar, Maharashtra',
    'Jammu, Jammu and Kashmir',
    'Sangli-Miraj & Kupwad, Maharashtra',
    'Mangalore, Karnataka',
    'Erode, Tamil Nadu',
    'Belgaum, Karnataka',
    'Ambattur, Tamil Nadu',
    'Tirunelveli, Tamil Nadu',
    'Malegaon, Maharashtra',
    'Gaya, Bihar',
    'Jalgaon, Maharashtra',
    'Udaipur, Rajasthan',
    'Maheshtala, West Bengal',
    'Tirupur, Tamil Nadu',
    'Davanagere, Karnataka',
    'Kozhikode, Kerala',
    'Kurnool, Andhra Pradesh',
    'Rajpur Sonarpur, West Bengal',
    'Bokaro Steel City, Jharkhand',
    'South Dumdum, West Bengal',
    'Bellary, Karnataka',
    'Patiala, Punjab',
    'Gopalpur, West Bengal',
    'Agartala, Tripura',
    'Bhagalpur, Bihar',
    'Muzaffarnagar, Uttar Pradesh',
    'Bhatpara, West Bengal',
    'Panihati, West Bengal',
    'Latur, Maharashtra',
    'Dhule, Maharashtra',
    'Rohtak, Haryana',
    'Korba, Chhattisgarh',
    'Bhilai Nagar, Chhattisgarh',
    'Brahmapur, Odisha',
    'Muzaffarpur, Bihar',
    'Ahmednagar, Maharashtra',
    'Mathura, Uttar Pradesh',
    'Kollam, Kerala',
    'Avadi, Tamil Nadu',
    'Kadapa, Andhra Pradesh',
    'Sambalpur, Odisha',
    'Bilaspur, Chhattisgarh',
    'Shahjahanpur, Uttar Pradesh',
    'Satara, Maharashtra',
    'Bijapur, Karnataka',
    'Rampur, Uttar Pradesh',
    'Shivamogga, Karnataka',
    'Chandrapur, Maharashtra',
    'Junagadh, Gujarat',
    'Thrissur, Kerala',
    'Alwar, Rajasthan',
    'Bardhaman, West Bengal',
    'Kulti, West Bengal',
    'Nizamabad, Telangana',
    'Parbhani, Maharashtra',
    'Tumkur, Karnataka',
    'Khammam, Telangana',
    'Ozhukarai, Puducherry',
    'Bihar Sharif, Bihar',
    'Panipat, Haryana',
    'Darbhanga, Bihar',
    'Bally, West Bengal',
    'Aizawl, Mizoram',
    'Dewas, Madhya Pradesh',
    'Ichalkaranji, Maharashtra',
    'Karnal, Haryana',
    'Bathinda, Punjab',
    'Jalna, Maharashtra',
    'Barasat, West Bengal',
    'Kirari Suleman Nagar, Delhi',
    'Purnia, Bihar',
    'Satna, Madhya Pradesh',
    'Mau, Uttar Pradesh',
    'Sonipat, Haryana',
    'Farrukhabad, Uttar Pradesh',
    'Sagar, Madhya Pradesh',
    'Rourkela, Odisha',
    'Durg, Chhattisgarh',
    'Imphal, Manipur',
    'Ratlam, Madhya Pradesh',
    'Hapur, Uttar Pradesh',
    'Arrah, Bihar',
    'Karimnagar, Telangana',
    'Anantapur, Andhra Pradesh',
    'Etawah, Uttar Pradesh',
    'Ambernath, Maharashtra',
    'North Dumdum, West Bengal',
    'Bharatpur, Rajasthan',
    'Begusarai, Bihar',
    'New Delhi, Delhi',
    'Chhapra, Bihar',
    'Kadiri, Andhra Pradesh',
    'Gandhinagar, Gujarat',
    'Baranagar, West Bengal',
    'Tiruvottiyur, Tamil Nadu',
    'Puducherry, Puducherry',
    'Sikar, Rajasthan',
    'Thoothukudi, Tamil Nadu',
    'Rewa, Madhya Pradesh',
    'Mirzapur, Uttar Pradesh',
    'Raichur, Karnataka',
    'Pali, Rajasthan',
    'Ramagundam, Telangana',
    'Haridwar, Uttarakhand',
    'Vijayanagaram, Andhra Pradesh',
    'Katihar, Bihar',
    'Nagercoil, Tamil Nadu',
    'Sri Ganganagar, Rajasthan',
    'Karawal Nagar, Delhi',
    'Mango, Jharkhand',
    'Bulandshahr, Uttar Pradesh',
    'Uluberia, West Bengal',
    'Katni, Madhya Pradesh',
    'Sambhal, Uttar Pradesh',
    'Singrauli, Madhya Pradesh',
    'Nadiad, Gujarat',
    'Secunderabad, Telangana',
    'Naihati, West Bengal',
    'Yamunanagar, Haryana',
    'Bidhan Nagar, West Bengal',
    'Pallavaram, Tamil Nadu',
    'Bidar, Karnataka',
    'Munger, Bihar',
    'Panchkula, Haryana',
    'Burhanpur, Madhya Pradesh',
    'Kharagpur, West Bengal',
    'Dindigul, Tamil Nadu',
    'Karnal, Haryana',
    'Morena, Madhya Pradesh',
    'Raigarh, Chhattisgarh',
    'Amroha, Uttar Pradesh',
    'Ongole, Andhra Pradesh',
    'Bharuch, Gujarat',
    'Navsari, Gujarat',
    'Malkajgiri, Telangana',
    'Saidapur, Uttar Pradesh',
    'Aurangabad, Bihar',
    'Bhind, Madhya Pradesh',
    'Bhusawal, Maharashtra',
    'Chandausi, Uttar Pradesh',
    'Ambala, Haryana',
    'Rewari, Haryana',
    'Gandhidham, Gujarat',
    'Baran, Rajasthan',
    'Nagaon, Assam',
    'Hazaribagh, Jharkhand',
    'Hajipur, Bihar',
    'Bhimavaram, Andhra Pradesh',
    'Khandwa, Madhya Pradesh',
    'Godhra, Gujarat',
    'Hoshiarpur, Punjab',
    'Tinsukia, Assam',
    'Jamalpur, Bihar',
    'Pudukkottai, Tamil Nadu',
    'Ettayapuram, Tamil Nadu',
    'Jagdalpur, Chhattisgarh',
    'Motihari, Bihar',
    'Dharmavaram, Andhra Pradesh',
    'Medinipur, West Bengal',
    'Habra, West Bengal',
    'Sasaram, Bihar',
    'Hajipur, Bihar',
    'Bhimavaram, Andhra Pradesh',
    'Adoni, Andhra Pradesh',
    'Madanapalle, Andhra Pradesh',
    'Siddipet, Telangana',
    'Alappuzha, Kerala',
    'Bahraich, Uttar Pradesh',
    'Tadepalligudem, Andhra Pradesh',
    'Reoti, Uttar Pradesh',
    'Narsinghpur, Madhya Pradesh',
    'Lalitpur, Uttar Pradesh',
    'Banda, Uttar Pradesh',
    'Orai, Uttar Pradesh',
    'Mahoba, Uttar Pradesh',
    'Hamirpur, Uttar Pradesh',
    'Fatehpur, Uttar Pradesh',
    'Banda, Uttar Pradesh',
    'Chitrakoot, Uttar Pradesh',
    'Karwi, Uttar Pradesh',
    'Manikpur, Uttar Pradesh',
    'Shahganj, Uttar Pradesh',
    'Tanda, Uttar Pradesh',
    'Akbarpur, Uttar Pradesh',
    'Bilhaur, Uttar Pradesh',
    'Kannauj, Uttar Pradesh',
    'Farrukhabad, Uttar Pradesh',
    'Etah, Uttar Pradesh',
    'Mainpuri, Uttar Pradesh',
    'Budaun, Uttar Pradesh',
    'Bareilly, Uttar Pradesh',
    'Pilibhit, Uttar Pradesh',
    'Shahjahanpur, Uttar Pradesh',
    'Lakhimpur, Uttar Pradesh',
    'Sitapur, Uttar Pradesh',
    'Hardoi, Uttar Pradesh',
    'Unnao, Uttar Pradesh',
    'Rae Bareli, Uttar Pradesh',
    'Pratapgarh, Uttar Pradesh',
    'Sultanpur, Uttar Pradesh',
    'Amethi, Uttar Pradesh',
    'Barabanki, Uttar Pradesh',
    'Faizabad, Uttar Pradesh',
    'Ambedkar Nagar, Uttar Pradesh',
    'Bahraich, Uttar Pradesh',
    'Shrawasti, Uttar Pradesh',
    'Balrampur, Uttar Pradesh',
    'Gonda, Uttar Pradesh',
    'Siddharthnagar, Uttar Pradesh',
    'Basti, Uttar Pradesh',
    'Sant Kabir Nagar, Uttar Pradesh',
    'Maharajganj, Uttar Pradesh',
    'Gorakhpur, Uttar Pradesh',
    'Kushinagar, Uttar Pradesh',
    'Deoria, Uttar Pradesh',
    'Padrauna, Uttar Pradesh',
    'Maharajganj, Uttar Pradesh',
    'Siddharthnagar, Uttar Pradesh',
    'Basti, Uttar Pradesh',
    'Sant Kabir Nagar, Uttar Pradesh',
    'Maharajganj, Uttar Pradesh',
    'Gorakhpur, Uttar Pradesh',
    'Kushinagar, Uttar Pradesh',
    'Deoria, Uttar Pradesh',
    'Padrauna, Uttar Pradesh',
    // Additional cities from various states
    'Shillong, Meghalaya',
    'Aizawl, Mizoram',
    'Kohima, Nagaland',
    'Itanagar, Arunachal Pradesh',
    'Gangtok, Sikkim',
    'Dispur, Assam',
    'Panaji, Goa',
    'Port Blair, Andaman and Nicobar Islands',
    'Kavaratti, Lakshadweep',
    'Daman, Daman and Diu',
    'Diu, Daman and Diu',
    'Pondicherry, Puducherry',
    'Karaikal, Puducherry',
    'Yanam, Puducherry',
    'Mahe, Puducherry',
    'Thiruvananthapuram, Kerala',
    'Kannur, Kerala',
    'Kottayam, Kerala',
    'Palakkad, Kerala',
    'Alappuzha, Kerala',
    'Pathanamthitta, Kerala',
    'Idukki, Kerala',
    'Wayanad, Kerala',
    'Kasargod, Kerala',
    'Malappuram, Kerala',
    'Ernakulam, Kerala',
    'Thrissur, Kerala',
    'Calicut, Kerala',
    'Kannur, Kerala',
    'Palakkad, Kerala',
    'Kollam, Kerala',
    'Trivandrum, Kerala',
    'Tiruppur, Tamil Nadu',
    'Erode, Tamil Nadu',
    'Salem, Tamil Nadu',
    'Coimbatore, Tamil Nadu',
    'Tirunelveli, Tamil Nadu',
    'Thanjavur, Tamil Nadu',
    'Kumbakonam, Tamil Nadu',
    'Kanchipuram, Tamil Nadu',
    'Vellore, Tamil Nadu',
    'Dindigul, Tamil Nadu',
    'Karur, Tamil Nadu',
    'Namakkal, Tamil Nadu',
    'Theni, Tamil Nadu',
    'Dharmapuri, Tamil Nadu',
    'Krishnagiri, Tamil Nadu',
    'Villupuram, Tamil Nadu',
    'Cuddalore, Tamil Nadu',
    'Nagapattinam, Tamil Nadu',
    'Thiruvarur, Tamil Nadu',
    'Pudukkottai, Tamil Nadu',
    'Sivaganga, Tamil Nadu',
    'Ramanathapuram, Tamil Nadu',
    'Virudhunagar, Tamil Nadu',
    'Tuticorin, Tamil Nadu',
    'Kanyakumari, Tamil Nadu',
    'The Nilgiris, Tamil Nadu',
    'Coimbatore, Tamil Nadu',
    'Tirupati, Andhra Pradesh',
    'Kurnool, Andhra Pradesh',
    'Kadapa, Andhra Pradesh',
    'Anantapur, Andhra Pradesh',
    'Chittoor, Andhra Pradesh',
    'Nellore, Andhra Pradesh',
    'Ongole, Andhra Pradesh',
    'Guntur, Andhra Pradesh',
    'Vijayawada, Andhra Pradesh',
    'Eluru, Andhra Pradesh',
    'Rajahmundry, Andhra Pradesh',
    'Kakinada, Andhra Pradesh',
    'Visakhapatnam, Andhra Pradesh',
    'Srikakulam, Andhra Pradesh',
    'Vizianagaram, Andhra Pradesh',
    'Warangal, Telangana',
    'Karimnagar, Telangana',
    'Nizamabad, Telangana',
    'Adilabad, Telangana',
    'Mahabubnagar, Telangana',
    'Medak, Telangana',
    'Nalgonda, Telangana',
    'Khammam, Telangana',
    'Ranga Reddy, Telangana',
    'Hyderabad, Telangana',
    'Secunderabad, Telangana',
    'Mysore, Karnataka',
    'Bangalore, Karnataka',
    'Mangalore, Karnataka',
    'Hubli, Karnataka',
    'Belgaum, Karnataka',
    'Gulbarga, Karnataka',
    'Davangere, Karnataka',
    'Bellary, Karnataka',
    'Bijapur, Karnataka',
    'Shimoga, Karnataka',
    'Tumkur, Karnataka',
    'Raichur, Karnataka',
    'Bidar, Karnataka',
    'Hassan, Karnataka',
    'Mandya, Karnataka',
    'Chikmagalur, Karnataka',
    'Udupi, Karnataka',
    'Chamarajanagar, Karnataka',
    'Kolar, Karnataka',
    'Chikkaballapur, Karnataka',
    'Ramanagara, Karnataka',
    'Chitradurga, Karnataka',
    'Bagalkot, Karnataka',
    'Gadag, Karnataka',
    'Haveri, Karnataka',
    'Dharwad, Karnataka',
    'Uttara Kannada, Karnataka',
    'Dakshina Kannada, Karnataka',
    'Kodagu, Karnataka',
    'Mumbai, Maharashtra',
    'Pune, Maharashtra',
    'Nagpur, Maharashtra',
    'Thane, Maharashtra',
    'Nashik, Maharashtra',
    'Aurangabad, Maharashtra',
    'Solapur, Maharashtra',
    'Amravati, Maharashtra',
    'Kolhapur, Maharashtra',
    'Sangli, Maharashtra',
    'Jalgaon, Maharashtra',
    'Akola, Maharashtra',
    'Latur, Maharashtra',
    'Ahmednagar, Maharashtra',
    'Chandrapur, Maharashtra',
    'Parbhani, Maharashtra',
    'Ichalkaranji, Maharashtra',
    'Jalna, Maharashtra',
    'Bhusawal, Maharashtra',
    'Panvel, Maharashtra',
    'Satara, Maharashtra',
    'Beed, Maharashtra',
    'Yavatmal, Maharashtra',
    'Kamptee, Maharashtra',
    'Gondia, Maharashtra',
    'Barshi, Maharashtra',
    'Achalpur, Maharashtra',
    'Osmanabad, Maharashtra',
    'Nandurbar, Maharashtra',
    'Wardha, Maharashtra',
    'Udgir, Maharashtra',
    'Aurangabad, Maharashtra',
    'Malegaon, Maharashtra',
    'Lonavla, Maharashtra',
    'Dehradun, Uttarakhand',
    'Haridwar, Uttarakhand',
    'Roorkee, Uttarakhand',
    'Haldwani, Uttarakhand',
    'Rudrapur, Uttarakhand',
    'Kashipur, Uttarakhand',
    'Rishikesh, Uttarakhand',
    'Ramnagar, Uttarakhand',
    'Pithoragarh, Uttarakhand',
    'Almora, Uttarakhand',
    'Nainital, Uttarakhand',
    'Mussoorie, Uttarakhand',
    'Chandigarh, Punjab',
    'Ludhiana, Punjab',
    'Amritsar, Punjab',
    'Jalandhar, Punjab',
    'Patiala, Punjab',
    'Bathinda, Punjab',
    'Pathankot, Punjab',
    'Hoshiarpur, Punjab',
    'Moga, Punjab',
    'Firozpur, Punjab',
    'Sangrur, Punjab',
    'Barnala, Punjab',
    'Faridkot, Punjab',
    'Fazilka, Punjab',
    'Gurdaspur, Punjab',
    'Kapurthala, Punjab',
    'Malerkotla, Punjab',
    'Muktsar, Punjab',
    'Nawanshahr, Punjab',
    'Rupnagar, Punjab',
    'S.A.S. Nagar, Punjab',
    'Tarn Taran, Punjab',
    'Jaipur, Rajasthan',
    'Jodhpur, Rajasthan',
    'Kota, Rajasthan',
    'Bikaner, Rajasthan',
    'Ajmer, Rajasthan',
    'Udaipur, Rajasthan',
    'Bhilwara, Rajasthan',
    'Alwar, Rajasthan',
    'Bharatpur, Rajasthan',
    'Sikar, Rajasthan',
    'Pali, Rajasthan',
    'Tonk, Rajasthan',
    'Churu, Rajasthan',
    'Hanumangarh, Rajasthan',
    'Sri Ganganagar, Rajasthan',
    'Jhunjhunu, Rajasthan',
    'Nagaur, Rajasthan',
    'Banswara, Rajasthan',
    'Baran, Rajasthan',
    'Barmer, Rajasthan',
    'Bundi, Rajasthan',
    'Chittorgarh, Rajasthan',
    'Dausa, Rajasthan',
    'Dholpur, Rajasthan',
    'Dungarpur, Rajasthan',
    'Jaisalmer, Rajasthan',
    'Jalore, Rajasthan',
    'Jhalawar, Rajasthan',
    'Karauli, Rajasthan',
    'Pratapgarh, Rajasthan',
    'Rajsamand, Rajasthan',
    'Sawai Madhopur, Rajasthan',
    'Sirohi, Rajasthan',
    'Dungarpur, Rajasthan',
    'Banswara, Rajasthan',
    'Ahmedabad, Gujarat',
    'Surat, Gujarat',
    'Vadodara, Gujarat',
    'Rajkot, Gujarat',
    'Bhavnagar, Gujarat',
    'Jamnagar, Gujarat',
    'Gandhinagar, Gujarat',
    'Junagadh, Gujarat',
    'Gandhidham, Gujarat',
    'Nadiad, Gujarat',
    'Bharuch, Gujarat',
    'Anand, Gujarat',
    'Navsari, Gujarat',
    'Porbandar, Gujarat',
    'Godhra, Gujarat',
    'Palanpur, Gujarat',
    'Valsad, Gujarat',
    'Vapi, Gujarat',
    'Mehsana, Gujarat',
    'Bhuj, Gujarat',
    'Surendranagar, Gujarat',
    'Dahod, Gujarat',
    'Patan, Gujarat',
    'Morbi, Gujarat',
    'Veraval, Gujarat',
    'Bardoli, Gujarat',
    'Gondal, Gujarat',
    'Jetpur, Gujarat',
    'Botad, Gujarat',
    'Dhoraji, Gujarat',
    'Wankaner, Gujarat',
    'Mahuva, Gujarat',
    'Amreli, Gujarat',
    'Palitana, Gujarat',
    'Dhandhuka, Gujarat',
    'Dholka, Gujarat',
    'Borsad, Gujarat',
    'Ankleshwar, Gujarat',
    'Kalol, Gujarat',
    'Modasa, Gujarat',
    'Himatnagar, Gujarat',
    'Idar, Gujarat',
    'Dharampur, Gujarat',
    'Valsad, Gujarat',
    'Bilimora, Gujarat',
    'Uttarpara, West Bengal',
    'Serampore, West Bengal',
    'Chandannagar, West Bengal',
    'Bardhaman, West Bengal',
    'Durgapur, West Bengal',
    'Asansol, West Bengal',
    'Kharagpur, West Bengal',
    'Midnapore, West Bengal',
    'Jalpaiguri, West Bengal',
    'Malda, West Bengal',
    'Berhampore, West Bengal',
    'Krishnanagar, West Bengal',
    'Baharampur, West Bengal',
    'Balurghat, West Bengal',
    'Raiganj, West Bengal',
    'Dalkhola, West Bengal',
    'Islampur, West Bengal',
    'Jangipur, West Bengal',
    'Murshidabad, West Bengal',
    'Nabadwip, West Bengal',
    'Santipur, West Bengal',
    'Ranaghat, West Bengal',
    'Bongaon, West Bengal',
    'Barrackpore, West Bengal',
    'Naihati, West Bengal',
    'Bhatpara, West Bengal',
    'Kamarhati, West Bengal',
    'Panihati, West Bengal',
    'Uttarpara, West Bengal',
    'Rishra, West Bengal',
    'Serampore, West Bengal',
    'Chandannagar, West Bengal',
    'Bansberia, West Bengal',
    'Hugli-Chinsurah, West Bengal',
    'Bhadreswar, West Bengal',
    'Baidyabati, West Bengal',
    'Jagatdal, West Bengal',
    'Naihati, West Bengal',
    'Khardaha, West Bengal',
    'Panihati, West Bengal',
    'Kamarhati, West Bengal',
    'Barrackpore, West Bengal',
    'Titagarh, West Bengal',
    'Bhatpara, West Bengal',
    'Panihati, West Bengal',
    'Khardaha, West Bengal',
    'Rajarhat Gopalpur, West Bengal',
    'Bidhannagar, West Bengal',
    'Dum Dum, West Bengal',
    'Barasat, West Bengal',
    'Madhyamgram, West Bengal',
    'Kolkata, West Bengal',
    'Howrah, West Bengal',
    'Kolkata, West Bengal',
    'Patna, Bihar',
    'Gaya, Bihar',
    'Bhagalpur, Bihar',
    'Muzaffarpur, Bihar',
    'Purnia, Bihar',
    'Darbhanga, Bihar',
    'Bihar Sharif, Bihar',
    'Arrah, Bihar',
    'Begusarai, Bihar',
    'Katihar, Bihar',
    'Munger, Bihar',
    'Chhapra, Bihar',
    'Motihari, Bihar',
    'Hajipur, Bihar',
    'Sitamarhi, Bihar',
    'Samastipur, Bihar',
    'Saharsa, Bihar',
    'Madhepura, Bihar',
    'Supaul, Bihar',
    'Araria, Bihar',
    'Kishanganj, Bihar',
    'Purnia, Bihar',
    'Katihar, Bihar',
    'Madhepura, Bihar',
    'Saharsa, Bihar',
    'Darbhanga, Bihar',
    'Muzaffarpur, Bihar',
    'Vaishali, Bihar',
    'Sitamarhi, Bihar',
    'Sheohar, Bihar',
    'East Champaran, Bihar',
    'West Champaran, Bihar',
    'Gopalganj, Bihar',
    'Siwan, Bihar',
    'Saran, Bihar',
    'Bhojpur, Bihar',
    'Buxar, Bihar',
    'Kaimur, Bihar',
    'Rohtas, Bihar',
    'Aurangabad, Bihar',
    'Gaya, Bihar',
    'Nawada, Bihar',
    'Jamui, Bihar',
    'Jehanabad, Bihar',
    'Arwal, Bihar',
    'Banka, Bihar',
    'Bhagalpur, Bihar',
    'Munger, Bihar',
    'Lakhisarai, Bihar',
    'Sheikhpura, Bihar',
    'Nalanda, Bihar',
    'Patna, Bihar',
    'Bhojpur, Bihar',
    'Buxar, Bihar',
    'Kaimur, Bihar',
    'Rohtas, Bihar',
    'Bhopal, Madhya Pradesh',
    'Indore, Madhya Pradesh',
    'Gwalior, Madhya Pradesh',
    'Jabalpur, Madhya Pradesh',
    'Raipur, Chhattisgarh',
    'Bhilai, Chhattisgarh',
    'Korba, Chhattisgarh',
    'Durg, Chhattisgarh',
    'Rajnandgaon, Chhattisgarh',
    'Raigarh, Chhattisgarh',
    'Jagdalpur, Chhattisgarh',
    'Ambikapur, Chhattisgarh',
    'Bilaspur, Chhattisgarh',
    'Dhamtari, Chhattisgarh',
    'Mahasamund, Chhattisgarh',
    'Kanker, Chhattisgarh',
    'Kondagaon, Chhattisgarh',
    'Narayanpur, Chhattisgarh',
    'Bijapur, Chhattisgarh',
    'Dantewada, Chhattisgarh',
    'Sukma, Chhattisgarh',
    'Bastar, Chhattisgarh',
    'Koriya, Chhattisgarh',
    'Surajpur, Chhattisgarh',
    'Balrampur, Chhattisgarh',
    'Surguja, Chhattisgarh',
    'Jashpur, Chhattisgarh',
    'Raigarh, Chhattisgarh',
    'Ranchi, Jharkhand',
    'Jamshedpur, Jharkhand',
    'Dhanbad, Jharkhand',
    'Bokaro Steel City, Jharkhand',
    'Hazaribagh, Jharkhand',
    'Giridih, Jharkhand',
    'Deoghar, Jharkhand',
    'Phusro, Jharkhand',
    'Adityapur, Jharkhand',
    'Chas, Jharkhand',
    'Chirkunda, Jharkhand',
    'Dumka, Jharkhand',
    'Medininagar, Jharkhand',
    'Chaibasa, Jharkhand',
    'Jhumri Tilaiya, Jharkhand',
    'Lohardaga, Jharkhand',
    'Gumla, Jharkhand',
    'Simdega, Jharkhand',
    'Khunti, Jharkhand',
    'West Singhbhum, Jharkhand',
    'Seraikela Kharsawan, Jharkhand',
    'East Singhbhum, Jharkhand',
    'Bhubaneswar, Odisha',
    'Cuttack, Odisha',
    'Rourkela, Odisha',
    'Brahmapur, Odisha',
    'Sambalpur, Odisha',
    'Puri, Odisha',
    'Baleshwar, Odisha',
    'Baripada, Odisha',
    'Bhadrak, Odisha',
    'Balangir, Odisha',
    'Jharsuguda, Odisha',
    'Bargarh, Odisha',
    'Sundargarh, Odisha',
    'Deogarh, Odisha',
    'Jajpur, Odisha',
    'Dhenkanal, Odisha',
    'Anugul, Odisha',
    'Kendujhar, Odisha',
    'Mayurbhanj, Odisha',
    'Baleshwar, Odisha',
    'Bhadrak, Odisha',
    'Kendrapara, Odisha',
    'Jagatsinghpur, Odisha',
    'Cuttack, Odisha',
    'Jajpur, Odisha',
    'Dhenkanal, Odisha',
    'Anugul, Odisha',
    'Deogarh, Odisha',
    'Angul, Odisha',
    'Dhenkanal, Odisha',
    'Cuttack, Odisha',
    'Jagatsinghpur, Odisha',
    'Kendrapara, Odisha',
    'Bhadrak, Odisha',
    'Baleshwar, Odisha',
    'Mayurbhanj, Odisha',
    'Kendujhar, Odisha',
    'Sundargarh, Odisha',
    'Sambalpur, Odisha',
    'Jharsuguda, Odisha',
    'Debagarh, Odisha',
    'Bargarh, Odisha',
    'Balangir, Odisha',
    'Nuapada, Odisha',
    'Kalahandi, Odisha',
    'Rayagada, Odisha',
    'Koraput, Odisha',
    'Malkangiri, Odisha',
    'Nabarangpur, Odisha',
    'Kandhamal, Odisha',
    'Boudh, Odisha',
    'Subarnapur, Odisha',
    'Bargarh, Odisha',
    'Jharsuguda, Odisha',
    'Sambalpur, Odisha',
    'Debagarh, Odisha',
    'Sundargarh, Odisha',
    'Kendujhar, Odisha',
    'Mayurbhanj, Odisha',
    'Baleshwar, Odisha',
    'Bhadrak, Odisha',
    'Kendrapara, Odisha',
    'Jagatsinghpur, Odisha',
    'Cuttack, Odisha',
    'Jajpur, Odisha',
    'Dhenkanal, Odisha',
    'Anugul, Odisha',
    'Nayagarh, Odisha',
    'Khordha, Odisha',
    'Puri, Odisha',
    'Ganjam, Odisha',
    'Gajapati, Odisha',
    'Kandhamal, Odisha',
    'Boudh, Odisha',
    'Sonepur, Odisha',
    'Balangir, Odisha',
    'Nuapada, Odisha',
    'Kalahandi, Odisha',
    'Rayagada, Odisha',
    'Koraput, Odisha',
    'Malkangiri, Odisha',
    'Nabarangpur, Odisha',
    'Guwahati, Assam',
    'Silchar, Assam',
    'Dibrugarh, Assam',
    'Jorhat, Assam',
    'Nagaon, Assam',
    'Tinsukia, Assam',
    'Tezpur, Assam',
    'Bongaigaon, Assam',
    'Dhubri, Assam',
    'Goalpara, Assam',
    'Barpeta, Assam',
    'Nalbari, Assam',
    'Kamrup, Assam',
    'Darrang, Assam',
    'Sonitpur, Assam',
    'Lakhimpur, Assam',
    'Dhemaji, Assam',
    'Tinsukia, Assam',
    'Dibrugarh, Assam',
    'Sivasagar, Assam',
    'Jorhat, Assam',
    'Golaghat, Assam',
    'Karbi Anglong, Assam',
    'Dima Hasao, Assam',
    'Cachar, Assam',
    'Karimganj, Assam',
    'Hailakandi, Assam',
    'Imphal, Manipur',
    'Thoubal, Manipur',
    'Bishnupur, Manipur',
    'Churachandpur, Manipur',
    'Chandel, Manipur',
    'Ukhrul, Manipur',
    'Tamenglong, Manipur',
    'Senapati, Manipur',
    'Kangpokpi, Manipur',
    'Jiribam, Manipur',
    'Kakching, Manipur',
    'Kamjong, Manipur',
    'Noney, Manipur',
    'Pherzawl, Manipur',
    'Tengnoupal, Manipur',
    'Aizawl, Mizoram',
    'Lunglei, Mizoram',
    'Saiha, Mizoram',
    'Champhai, Mizoram',
    'Kolasib, Mizoram',
    'Serchhip, Mizoram',
    'Lawngtlai, Mizoram',
    'Mamit, Mizoram',
    'Kolasib, Mizoram',
    'Aizawl, Mizoram',
    'Lunglei, Mizoram',
    'Saiha, Mizoram',
    'Champhai, Mizoram',
    'Serchhip, Mizoram',
    'Lawngtlai, Mizoram',
    'Mamit, Mizoram',
    'Kohima, Nagaland',
    'Dimapur, Nagaland',
    'Mokokchung, Nagaland',
    'Tuensang, Nagaland',
    'Wokha, Nagaland',
    'Zunheboto, Nagaland',
    'Phek, Nagaland',
    'Kiphire, Nagaland',
    'Longleng, Nagaland',
    'Peren, Nagaland',
    'Mon, Nagaland',
    'Noklak, Nagaland',
    'Shamator, Nagaland',
    'Tseminyu, Nagaland',
    'Chumukedima, Nagaland',
    'Niuland, Nagaland',
    'Agartala, Tripura',
    'Udaipur, Tripura',
    'Dharmanagar, Tripura',
    'Kailasahar, Tripura',
    'Belonia, Tripura',
    'Khowai, Tripura',
    'Teliamura, Tripura',
    'Ambassa, Tripura',
    'Kumarghat, Tripura',
    'Sabroom, Tripura',
    'Bishalgarh, Tripura',
    'Sonamura, Tripura',
    'Melaghar, Tripura',
    'Kamalpur, Tripura',
    'Amarpur, Tripura',
    'Karbook, Tripura',
    'Gandacherra, Tripura',
    'Dumburnagar, Tripura',
    'Jampuijala, Tripura',
    'Jirania, Tripura',
    'Mohanpur, Tripura',
    'Hezamara, Tripura',
    'Tulashikhar, Tripura',
    'Panisagar, Tripura',
    'Kanchanpur, Tripura',
    'Dasda, Tripura',
    'Jampuijala, Tripura',
    'Jirania, Tripura',
    'Mohanpur, Tripura',
    'Hezamara, Tripura',
    'Tulashikhar, Tripura',
    'Panisagar, Tripura',
    'Kanchanpur, Tripura',
    'Dasda, Tripura',
    'Shillong, Meghalaya',
    'Tura, Meghalaya',
    'Jowai, Meghalaya',
    'Nongpoh, Meghalaya',
    'Nongstoin, Meghalaya',
    'Williamnagar, Meghalaya',
    'Resubelpara, Meghalaya',
    'Baghmara, Meghalaya',
    'Ampati, Meghalaya',
    'Mairang, Meghalaya',
    'Mawkyrwat, Meghalaya',
    'Nongpoh, Meghalaya',
    'Nongstoin, Meghalaya',
    'Williamnagar, Meghalaya',
    'Resubelpara, Meghalaya',
    'Baghmara, Meghalaya',
    'Ampati, Meghalaya',
    'Mairang, Meghalaya',
    'Mawkyrwat, Meghalaya',
    'Itanagar, Arunachal Pradesh',
    'Naharlagun, Arunachal Pradesh',
    'Pasighat, Arunachal Pradesh',
    'Tezu, Arunachal Pradesh',
    'Ziro, Arunachal Pradesh',
    'Along, Arunachal Pradesh',
    'Daporijo, Arunachal Pradesh',
    'Anini, Arunachal Pradesh',
    'Roing, Arunachal Pradesh',
    'Bomdila, Arunachal Pradesh',
    'Tawang, Arunachal Pradesh',
    'Seppa, Arunachal Pradesh',
    'Koloriang, Arunachal Pradesh',
    'Yingkiong, Arunachal Pradesh',
    'Changlang, Arunachal Pradesh',
    'Khonsa, Arunachal Pradesh',
    'Longding, Arunachal Pradesh',
    'Namsai, Arunachal Pradesh',
    'Hayuliang, Arunachal Pradesh',
    'Anjaw, Arunachal Pradesh',
    'Tuting, Arunachal Pradesh',
    'Geku, Arunachal Pradesh',
    'Mariyang, Arunachal Pradesh',
    'Yingkiong, Arunachal Pradesh',
    'Pasighat, Arunachal Pradesh',
    'Mebo, Arunachal Pradesh',
    'Namsai, Arunachal Pradesh',
    'Chowkham, Arunachal Pradesh',
    'Lekang, Arunachal Pradesh',
    'Namsai, Arunachal Pradesh',
    'Chowkham, Arunachal Pradesh',
    'Lekang, Arunachal Pradesh',
    'Gangtok, Sikkim',
    'Namchi, Sikkim',
    'Mangan, Sikkim',
    'Gyalshing, Sikkim',
    'Singtam, Sikkim',
    'Rangpo, Sikkim',
    'Jorethang, Sikkim',
    'Rhenock, Sikkim',
    'Rongli, Sikkim',
    'Pakyong, Sikkim',
    'Ravangla, Sikkim',
    'Namchi, Sikkim',
    'Mangan, Sikkim',
    'Gyalshing, Sikkim',
    'Singtam, Sikkim',
    'Rangpo, Sikkim',
    'Jorethang, Sikkim',
    'Rhenock, Sikkim',
    'Rongli, Sikkim',
    'Pakyong, Sikkim',
    'Ravangla, Sikkim',
    'Panaji, Goa',
    'Margao, Goa',
    'Vasco da Gama, Goa',
    'Mapusa, Goa',
    'Ponda, Goa',
    'Bicholim, Goa',
    'Valpoi, Goa',
    'Curchorem, Goa',
    'Quepem, Goa',
    'Canacona, Goa',
    'Sanguem, Goa',
    'Dharbandora, Goa',
    'Pernem, Goa',
    'Bardez, Goa',
    'Tiswadi, Goa',
    'Salcete, Goa',
    'Mormugao, Goa',
    'Sattari, Goa',
    'Canacona, Goa',
    'Quepem, Goa',
    'Sanguem, Goa',
    'Dharbandora, Goa',
    'Pernem, Goa',
    'Bardez, Goa',
    'Tiswadi, Goa',
    'Salcete, Goa',
    'Mormugao, Goa',
    'Sattari, Goa'
  ];

  constructor() { }

  searchCities(query: string): string[] {
    if (!query || query.trim().length < 2) {
      return [];
    }

    const lowerQuery = query.toLowerCase().trim();
    return this.cities
      .filter(city => city.toLowerCase().includes(lowerQuery))
      .slice(0, 10); // Limit to 10 results
  }

  getAllCities(): string[] {
    return [...this.cities];
  }
}
